services:
  springapp:
    container_name: springboot_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/uploads  # Mount the uploads directory to persist files
    environment:
      - SPRING_SERVLET_MULTIPART_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=100MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=100MB
      - SERVER_PORT=8080
    networks:
      - spring-boot-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the custom NGINX configuration file
      - ./frontend:/usr/share/nginx/html  # Mount the frontend directory to serve static files
    ports:
      - 80:80  # Expose port 80 for HTTP traffic
    depends_on:
      - springapp
    networks:
      - spring-boot-network

networks:
  spring-boot-network:
    driver: bridge #default value is eh bridge